---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 25.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: America/Los_Angeles
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    workload:
      main:
        replicas: 2
        strategy: RollingUpdate
        podSpec:
          containers:
            main:
              command:
                - authelia
              args:
                - --config=/configuration.yaml
              envFrom:
                - configMapRef:
                    name: authelia-paths
              probes:
                liveness:
                  type: http
                  path: "/api/health"
                readiness:
                  type: http
                  path: "/api/health"
                startup:
                  type: http
                  path: "/api/health"
    service:
      main:
        ports:
          main:
            port: 9091
            targetPort: 9091
    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
    cnpg:
      main:
        # mode: recovery
        cluster:
          singleNode: true
        backups:
          enabled: true
          credentials: s3
        recovery:
          method: object_store
          credentials: s3
    redis:
      enabled: true
      includeCommon: true
    domain: ${DOMAIN_0}
    server:
      port: 9091
      read_buffer_size: 4096
      write_buffer_size: 4096
      path: ""
    log:
      level: trace
      format: text
    default_redirection_url: "${AUTH_URL}"
    theme: dark
    totp:
      issuer: ${BASE_DOMAIN}
      period: 30
      skew: 1
    password_policy:
      standard:
        enabled: false
        min_length: 8
        max_length: 0
        require_uppercase: false
        require_lowercase: false
        require_number: false
        require_special: false
      zxcvbn:
        enabled: false
        min_score: 3
    duo_api:
      enabled: false
      hostname: api-123456789.example.com
      integration_key: ABCDEF
      plain_api_key: ""
    ntp:
      address: "time.cloudflare.com:123"
      version: 4
      max_desync: 3s
      disable_startup_check: false
      disable_failure: true
    authentication_backend:
      disable_reset_password: false
      refresh_interval: 5m
      ldap:
        enabled: true
        url: ldap://lldap-ldap.lldap.svc.cluster.local:3890
        timeout: 5s
        start_tls: false
        tls:
          server_name: ""
          skip_verify: false
          minimum_version: TLS1.2
        base_dn: ${LLDAP_LDAP_BASE_DN}
        username_attribute: "uid"
        additional_users_dn: ou=people
        users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
        additional_groups_dn: ou=groups
        groups_filter: "(member={dn})"
        group_name_attribute: "cn"
        mail_attribute: "mail"
        display_name_attribute: "displayName"
        user: ${AUTH_USER}
        plain_password: ${AUTH_PASS}
      file:
        enabled: false
        path: /config/users_database.yml
        password:
          algorithm: argon2id
          iterations: 1
          key_length: 32
          salt_length: 16
          memory: 1024
          parallelism: 8

    access_control:
      default_policy: two_factor
      networks_access_control: []

      rules: []
    session:
      name: authelia_session
      same_site: lax
      expiration: 1h
      inactivity: 5m
      remember_me_duration: 1M
    redisProvider:
      port: 6379
      username: ""
      maximum_active_connections: 8
      minimum_idle_connections: 0
      tls:
        enabled: false
        server_name: ""
        skip_verify: false
        minimum_version: TLS1.2
      high_availability:
        enabled: false
        enabledSecret: false
        sentinel_name: mysentinel
        nodes: []
        route_by_latency: false
        route_randomly: false
    regulation:
      max_retries: 3
      find_time: 2m
      ban_time: 5m
    storage:
      postgres:
        port: 5432
        database: authelia
        username: authelia
        sslmode: disable
        timeout: 5s
    notifier:
      disable_startup_check: false
      filesystem:
        enabled: false
        filename: /config/notification.txt
      smtp:
        enabled: true
        enabledSecret: false
        host: smtp.gmail.com
        port: 587
        timeout: 5s
        username: ${DOMAIN_0_EMAIL}
        plain_password: ${GMAIL_PASS}
        sender: ${DOMAIN_0_EMAIL}
        identifier: localhost
        subject: "[Authelia] {title}"
        startup_check_address: test@authelia.com
        disable_require_tls: false
        disable_html_emails: false
        tls:
          server_name: ""
          skip_verify: false
          minimum_version: TLS1.2
    identity_providers:
      oidc:
        enabled: false
        access_token_lifespan: 1h
        authorize_code_lifespan: 1m
        id_token_lifespan: 1h
        refresh_token_lifespan: 90m
        enable_client_debug_messages: false
        minimum_parameter_entropy: 8
        clients: []
    portal:
      open:
        enabled: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: auth.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - auth.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard

