---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbt4kdown
  namespace: qbt4kdown
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: qbt4kdown-qbittorrent
            patch: |
              - op: add
                path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
                value: 1
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.1.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: America/Los_Angeles
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    qbitportforward:
      enabled: false
      QBT_USERNAME: "admin"
      QBT_PASSWORD: "adminadmin"
    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - "192.168.254.0/24"
        excludedNetworks_IPv6: []
        env:
          VPN_SERVICE_PROVIDER: airvpn
          DOT: on
          DNS_KEEP_NAMESERVER: on
          FIREWALL_OUTBOUND_SUBNETS: 192.168.254.0/24,172.16.0.0/12
          
          FIREWALL_INPUT_PORTS: 10095,8000
          SERVER_NAMES: Baiten
          VPN_TYPE: wireguard
          WIREGUARD_ADDRESSES: 10.128.146.241/32
          WIREGUARD_PRESHARED_KEY: ${WIREGUARD_PRESHARED_KEY}
          WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}

    persistence:
      config:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
      downloads:
        enabled: true
        path: /mnt/sas12st/qbttemp
        mountPath: /media
        server: 192.168.254.10
        type: nfs
      completed:
        enabled: true
        path: /mnt/sas10/4kdown
        mountPath: /opt
        server: 192.168.254.10
        type: nfs
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
              - name: auth
        hosts:
          - host: qbt.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - qbt.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        
