apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dOqSNDZgcHYY+0T2WW1E2FbhGCR+Z+jON758f62AV19rNYKP3LR1gzSGUWoQ/HypPaWgySHfKVekLDztCOvRTORfD1izu6EPhFtC5u7AXetsCv7AkJGs1bbFqWtYUAwYtjE3aN3+Qzx64s9Dm+Oh8T6qNASbF8q+pMyYL1CQu1Elh+CjVdvxbYMT09+QWs+kCh0hF6xRSzxsNaypcDGr2sgoN6BPSginvHcNGSE/pR92qljKiaZCqKmGouT03txBMhWnAzp0bUVLLhsSQnf16Uea3/r+VSS8qSa3sIz8FrXSNnTkuL8oxUIvOprRRCLUOk6ZxzDw13qlhygQo72SJ6MiHYcxxgNPMWI+nLFZPmoZRny0FDpmpgf0GqjG/lz/,iv:2T7p2qh7n7zom8PVagM4vZQJjR95Kj0jcyWxJAZyG3U=,tag:+ocCSjQmlF9JJr0ddjX+wg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Y2cjNK3kFVcqXAuUZq8QIDSdXcu70EC2dXl1RUJzIk4TXMAOYVEGioFZtCOWM55+tEEfG3SXxBGrxnzc8AH30hDJVUvvf5na/23nEF+LhtCqYghCjqntzqJI9LMAHpzRbReo+gMwO7uM9nd7Rxlhpw6thccJwhVuVp99AGc1dmPYLm3Mt2A2wn/2W0Voc6LeN8g3gbMFkHptSFFEIUsL1eoaJ7S39Gedky+yutbeX13NjbNA+qjR+oNjICM3xMCsTOwobOgPBdwYBvSb2A==,iv:qI0suX/E4TiUuUrV7raoULUuNnqyu8LGctzp9KplWdI=,tag:8qwRQqYRLzJDWalFYxndBA==,type:str]
    known_hosts: ENC[AES256_GCM,data:QBP/Vj/ivuBkfjuobp78fdsE1HtTGa2l7Np0eoQm89g4yAWe6TauinXZMVwarbMOqrS28TQpCznN21CMpe5e1kplZXxP0fJrHxAGEtQ1Y+YpEk0WLwfSykanFl7/8WBm7FEONcAo6ExzAyJskKTsmgZRyF36O6eCJ8QYdjjJ1pO/R+yT3QmLAbVo+eV/LzSgOq46edbFGg8pMj4YF96Epk5xCgRaCe0zjZVf,iv:mYWWIk6Ya7UT1wKUUWtFAt2fJl6Fla+d/cB95oxVv8E=,tag:ayYbVvjxq/QbwCkR4DaMvw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kwccq6ppa0crsk5pcs7unph68mchlmdlp2tupw2t9axz34rppy8qkq5gnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT1FOQ28rV2pTZThUd3Ft
            ekdubWNwak5QSVpGUjhVVmd1V05rVVYyZTFVClg5b2FYQVVCYTdRbEVIa3E0eHBv
            T2Q4dGFzTTRmcmFjRFhEcmUyOGpuaWMKLS0tIDJoR216dHhqQ21oeE8ySllPLytX
            MFdhNWlKeG5TSy9MTDNaZnkycXFTMUkK0cUuLqsefl4eGeyTMRIRkz6W9/OV9Qkb
            b5RP7gZZVYP+IjT2fyAin2YJ2qLlwth3Nmz9g2mtDrvnO+SgLMmzyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T15:45:48Z"
    mac: ENC[AES256_GCM,data:W2YeKVmmPw3JtQ3LVLB02OK9PFq4vVrKtVVGOWARl1nfLEra4wnrFbtAPzS7DsiX4zOHFKRSAiXyYwl8ccS01IT5cHNwrx11sRhAzEZGgGlpxGgUk0/xTF/b9ewGR67j5f428ucIVqdkm2n5Tkj5chaj9ceIQc/EQcUa7zofLSw=,iv:IWc3Vxe+5/bd0vHx11ClZ3GjY5hnhA5F1ayAPiL/vnc=,tag:cvp/w71X9tLHTJco94kCZg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
