apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FymjOQ4juLizUdjz57Zx7L3CRCI43NB4jxOw1xwQZvIWdiP2mXh+vqKfdXwqZGvOjV4gh67G0o72+SMhfsua3NiQR6sjxrg1Pqlb3uA7nQjhgsWVLDqF5pwoz7hooSMPM5ZxABrz5OTgYW6ME9/Z9IfPMXBmGjdUTsynEsKHomttSS5fkwQJMTTPO8gmS8xBuS16O3GbLu/cNKw3sTyCKRj3qs96+2N+F79/H1xtr2mqdQ3+yCU/hUUBmkRarqBPkK67sZv8HOA0J3SGhUsNccyWI09CXnn6YJZmiB6gywCFivTCOzv65tAwoj/qw/6ldxQ/xEnOlC9yvB87xaKHUBNcSfJrBavpX57T2T9NnwnghGj2z9J+Ccmv94U10r5J,iv:lHEWIgfb4gNZcPEvO5P/g1CUjuTw1+aXCq08s4KtMWQ=,tag:SMQgGVXIxCpmyutgSTYtKw==,type:str]
    identity.pub: ENC[AES256_GCM,data:JxysCor4w9+Qo38cVg1F0I7Jp4oSFNnd99L4SCW4CHqaKRMsKz4s+5exGuHnXaVKmet3+8TxCWa37vEEWAoJ1IlgtLvk+pduIGLYvPYVWQwyr6ZKj3QvLwG8joiwN/O7pesny6KgP+/i7PwUYbCXdpaniOT7ousRIi7Eko20IFNWwSvFE5yxW5raY6ikNIAjW/CTwsc1DtsjpDpxgKJ9XKsukR573aEQ435NGUVsRKkrWJc8cLKihuiGYKBOazH7NiNOS5xmWGDu05M0ig==,iv:11T1z0EgK5YyaXdqNJQE2HlURTU3F3MtXsFUqEGnEYM=,tag:rwLDSwWu8E6o1j2G6DSBpg==,type:str]
    known_hosts: ENC[AES256_GCM,data:BG80tFhyrhgOLHokgB5D6fIFwa23Iip8uUCWTB+i0GYWEc4E9VLv63xPFXQwD5aZvU/JKyBI1rzKCPr71QhHAvz6+aLZVFI+G6Bjaw23QE1aoAHDI4iM1I8Yv5shJ183UTl8BzOBeFlwVCHNQprbBTtlAf9AjM3zTv1XBZ7wUgZKKdUuD+NFeAaLF94EyB1h6hsBCRVjVTlWghD/F0memLaj91ChMdGJ9ZXn,iv:Wjgfdo1PsbDjXLkGACcu1HTG3k+0zCseD9LL4L1xx9I=,tag:cLWqfggJTF5gpbObMnHcvg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kwccq6ppa0crsk5pcs7unph68mchlmdlp2tupw2t9axz34rppy8qkq5gnf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa3JXM0FCdW1ESFRrc0Iv
            a0dTZGFPZkZpaGIwdUczSUxPUURzaXFOZjFVCkhmU1VFSHJNZmtaUDBuRXlweWhP
            TjV0UTI0V2w4S21jVUVZZzhBb2VQYmcKLS0tIFQydkpmZ1l1SWhVNloyZDd4STBu
            bzYyNEdOWkhoeCsvZkdXUWhRTlo3YUkK+1czNl/gDrI/g5+iUNdUWS9P3ug/tLZM
            XCosIeD3sfjHWOtZ9xROhK/hcBlCXqwkNxqbodErGXreKypKGU2K6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T17:46:23Z"
    mac: ENC[AES256_GCM,data:scD0C9oTz3cQy1VfuIa9F0Po7oW/HNNaYIRoyJRbOdex0MKWXVmsBnSMYaH5aqNSE4/y9N8vZZpXnEDdOcAqZ8U7aJGLoBITeOQoMAQ4MfXdNYKmNJEvmAXa+Z3b6UdR04uvSqGel70bmrYKDM8ggXw1ZswqxiQ7i1VXWRMxqnA=,iv:e9XVEpHfPIWa5PnHJqygjA6Nz6WNC7xWL7tAHo5/XLM=,tag:kaPHunFdhexsgzsIfj0T4w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
