---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 19.3.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:  
    global:
      stopAll: false  
    TZ: Europe/Brussels
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    plex:
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL:
      disableGDM: true
      requireHTTPS: false
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}       
    persistence:
      config:
        size: 200Gi
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true        
      4kseed:
        enabled: true
        path: /mnt/sas20/4kseed
        mountPath: /media
        server: 192.168.254.10
        type: nfs
      4kdown:
        enabled: true
        path: /mnt/sas10/4kdown
        mountPath: /home
        server: 192.168.254.10
        type: nfs
      4kremux:
         enabled: true
         path: /mnt/sas10/4kremux
         mountPath: /opt
         server: 192.168.254.10
         type: nfs
      10bit:
         enabled: true
         path: /mnt/sas12st/10bit
         mountPath: /srv
         server: 192.168.254.10
         type: nfs
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
        hosts:
          - host: plex.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - plex.${DOMAIN_0}
            clusterIssuer: cluster-cert
