---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: generic-device-plugin
  namespace: generic-device-plugin
spec:
  interval: 15m
  chart:
    spec:
      chart: generic-device-plugin
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    portal:
    open:
      enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              args:
                - --domain
                - truecharts.org
                - --device
                - |
                  name: tun
                  groups:
                    - count: 1000
                      paths:
                        - path: /dev/net/tun
    securityContext:
      container:
        readOnlyRootFilesystem: true
        privileged: true
        runAsNonRoot: false
        runAsGroup: 0
        runAsUser: 0
    persistence:
      dev:
        enabled: true
        type: hostPath
        hostPath: /dev
        mountPath: /dev
      device-plugin:
        enabled: true
        type: hostPath
        hostPath: /var/lib/kubelet/device-plugins
        mountPath: /var/lib/kubelet/device-plugins
    service:
      main:
        ports:
          main:
            port: 8080
            protocol: tcp
                      
 
 
  
