---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.4.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## set stopAll to "true" if you do not want to use traefik
    # and/or disable its service
    global:
      stopAll: false
    defaultCertificate: "domain-0-wildcard"
    service:
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
              - traefik.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: traefik.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    middlewares:
      ipWhiteList:
        - name: local
          sourceRange:
            - 172.16.0.0/16
            - 172.17.0.0/16
            - 192.168.254.0/24
            - 10.10.1.0/24
      forwardAuth:
        - name: auth
          address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://auth.${DOMAIN_0}/
          authResponseHeaders:
              # X-authentik-username
              # X-authentik-groups
              # X-authentik-email
              # X-authentik-name
              # X-authentik-uid
              # X-authentik-jwt
              # X-authentik-meta-jwks
              - Remote-Email
              - Remote-Name
              - Remote-Groups
              - Remote-User
          trustForwardHeader: true
          tls:
            insecureSkipVerify: true
      
