---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: vaultwarden
      version: 28.4.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false    
    TZ: Europe/Brussels
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    database:
      type: postgresql
      wal: true
    vaultwarden:
      allowSignups: false
      verifySignup: false
      requireEmail: false
      allowInvitation: true
      showPasswordHint: false
      enableWebVault: true
      orgCreationUsers: all
      admin:
        enabled: true
        disableAdminToken: false
        token: ${VAULT_PASS}
      smtp:
        enabled: false
        host: smtp.gmail.com
        from: ${EMAIL}
        fromName: sas
        security: starttls
        ## SMTP port. Defaults to 587 with STARTTLS, 465 with FORCE_TLS, and 25 without SSL.
        port: 587
        ## SMTP Authentication Mechanisms. Comma-separated options: 'Plain', 'Login' and 'Xoauth2'. Defaults to 'Plain'.
        uthMechanism: Plain
        ## Hostname to be sent for SMTP HELO. Defaults to pod name.
        heloName: Vault
        ## SMTP timeout.
        timeout: 15
        ## Accept SSL session if certificate is valid but hostname doesn't match. DANGEROUS, vulnerable to men-in-the-middle attacks!
        invalidHostname: false
        ## Accept invalid certificates. DANGEROUS, vulnerable to men-in-the-middle attacks!
        invalidCertificate: false
        ## SMTP username.
        user: ${EMAIL}
        ## SMTP password. Required is user is specified, ignored if no user provided.
        password: ${VAULT_GMAIL_PASS}
      yubico:
        enabled: false
      push:
        enabled: false
      log:
        file: 
        level: trace
      icons:
        disableDownload: false
    persistence:
      data:
        volsync:
          - name: b2
            type: restic
            credentials: s3
            dest:
              enabled: true                          
            src:
              enabled: true
    cnpg:
      main:
        # mode: recovery
        backups:
          enabled: true
          credentials: s3
        recovery:
          method: object_store
          credentials: s3
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: auth
                namespace: traefik
              - name: local
                namespace: traefik
        hosts:
          - host: vault.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix    
        tls:
          - hosts:
              - vault.${DOMAIN_0}
            clusterIssuer: cluster-cert
